{% set name = "ANTs" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ANTsX/ANTs/archive/v{{ version }}.tar.gz
  sha256: fc5db651c65855b553d21ca4de9ac2ce2078e7406b4eff5602d5ae8d0c2ea75d

build:
  number: 1  # Increment build number for Conda to detect the change
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.16.3
    - ninja
  host:
    - libboost-headers
    - libitk-devel=5.4.0
  run:
    - libitk=5.4.0

test:
  commands:
    - antsRegistration --help

about:
  home: https://stnava.github.io/ANTs/
  license: Apache-2.0
  license_file: COPYING.txt
  summary: >
    ANTs computes high-dimensional mappings to capture the statistics of brain structure and function
  doc_url: http://stnava.github.io/ANTsDoc
  dev_url: https://github.com/ANTsX/ANTs/wiki

extra:
  recipe-maintainers:
    - ghisvail
